### ISSUE TITLE
Add a generic tag helper for umbnav items

### ISSUE THREAD

**Issue by tzbarkan** [AaronSadlerUK/Our.Umbraco.UmbNav#16]
The method to build a tag for any UmbNavItem is to use item.getLinkHtml(), there doesn't appear to be any comparable helper for labels. Calling someLabel.getLinkHtml() is somehwat confusing for rendering an inert label.

It would be handy if there were a helper like item.getItemHtml() which would render the appropriate html based on the umbnav itemtype.

**Comment by AaronSadlerUK** [comment]
Great idea!

**Comment by AaronSadlerUK** [comment]
On looking it turns out this should already do this, in my tests it works correctly.

https://github.com/AaronSadlerUK/Our.Umbraco.UmbNav/blob/95edc04f68ad32be9313a72e22c1d910eaa657f2/src/UmbNav.Core/Extensions/UmbNavItemExtensions.cs#L27-L30

So much like #13 I have a feeling this is a cache issue your end.

I have however added an extension with a generic name of GetItemHtml but this just maps to GetLinkHtml

**Comment by tzbarkan** [comment]
It was working for us (when other things were working). This enhancement was more about not having to use getLinkHtml to render a non link item. :) The extension satisfies the feature request for me. Thanks!
