### ISSUE TITLE
Test Site fails to build - Metadata file 'C:\Users\mike\.nuget\packages\lucene.net\3.0.3\analyzers\dotnet\cs\Lucene.Net.CodeAnalysis.CSharp.dll' could not be found	UmbNav.Core (net50)	

### ISSUE THREAD

**Issue by mistyn8** [AaronSadlerUK/Our.Umbraco.UmbNav#3]
Metadata file 'C:\Users\mike\.nuget\packages\lucene.net\3.0.3\analyzers\dotnet\cs\Lucene.Net.CodeAnalysis.CSharp.dll' could not be found	UmbNav.Core (net50)	

clone repo and try to run either test site.

Sorry if this is a simple fix, but I'm not up to date with multitargetted package creation.

I tried adding.. `<PackageReference Include="Lucene.Net" Version="4.8.0-beta00014" PrivateAssets="all" />` as suggested elsewhere but doesn't seem to resolve

**Comment by AaronSadlerUK** [comment]
So this was being spoken about in a discussion on the Slack channel recently:

https://umbracians.slack.com/archives/C06G5LWBV/p1627070995147300

It turns out there is a "bodge" for this which [mattbrailsford](https://twitter.com/mattbrailsford) found that if you copy the analysers folder from the v4 folder into the v3 one then it works.

**Comment by mistyn8** [comment]
Thanks for the heads up on the #help channel on slack... had joined but only thought there was #general and #announcements!!! lots more channels to join now :-)

ps `CMD > dotnet run`  seems fine???

**Comment by AaronSadlerUK** [comment]
There are loads of channels, I only watch the ones I'm interested in 😅

I just use the VS build / run thing, it's a core issue by the looks of it, but I've fixed it on my PC and Build Server, I'll be sure to mention it in the documentation too
